[package]
name = "krustlet"
version = "0.2.1"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"
default-run = "krustlet-wascc"
license-file = "LICENSE"
description = "A Kubernetes kubelet implementation in Rust, used for running WebAssembly modules in Kubernetes"
repository = "https://github.com/deislabs/krustlet"
documentation = "https://github.com/deislabs/krustlet/tree/master/docs"
readme = "README.md"
keywords = [
    "wasm",
    "wasi",
    "webassembly",
    "kubernetes",
]
exclude = [
    "docs/*",
    "demos/*",
    ".github/*",
    ".gitignore"
]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0"
tokio = { version = "0.2", features = ["macros"] }
kube = "0.34"
env_logger = "0.7"
kubelet = { path = "./crates/kubelet", version = "0.2", features = ["cli"] }
wascc-provider = { path = "./crates/wascc-provider", version = "0.2" }
wasi-provider = { path = "./crates/wasi-provider", version = "0.2" }
oci-distribution = { path = "./crates/oci-distribution", version = "0.1" }

[dev-dependencies]
futures = "0.3"
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
k8s-openapi = { version = "0.7.1", default-features = false, features = ["v1_17"] }
reqwest = "0.10"
dirs = "2.0"
tempfile = "3.1"

[workspace]
members = [
    "crates/*"
]

[[bin]]
name = "krustlet-wascc"
path = "src/krustlet-wascc.rs"

[[bin]]
name = "krustlet-wasi"
path = "src/krustlet-wasi.rs"
