apiVersion: v1
kind: Pod
metadata:
  name: greet
  annotations:
    deislabs.io/wascc-action-key: MADK3R3H47FGXN5F4HWPSJH4WCKDWKXQBBIOVI7YEPEYEMGJ2GDFIFE5

spec:
  containers:
    - image: greet_actor_signed.wasm
      imagePullPolicy: Always
      name: greet
      ports:
        - containerPort: 80
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    beta.kubernetes.io/arch: wasm32-wascc
