apiVersion: v1
kind: Pod
metadata:
  name: greet
spec:
  containers:
    - image: webassembly.azurecr.io/hello-wasm:v1
      imagePullPolicy: Always
      name: greet
      ports:
        - containerPort: 80
  tolerations:
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "krustlet/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
