apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      ports:
        - containerPort: 80
        - containerPort: 443
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: krustlet
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
    - key: hashicorp.com/nomad
      effect: NoSchedule
